### ISSUE TITLE
No inicia ._.

### ISSUE THREAD

**Issue by Rhozlid** [MrJmpl3/J3Ultimate-1.7.10#1]
Al intentar iniciar esa version con java 6 me da un error:

java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$000(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
Exception in thread "main"

y al intentar abrirlo con java 7 solo no se abre, el Log del launcher se queda en blanco y el juego nunca inicia ._.

**Comment by Rhozlid** [comment]
me equivoque ._. esto era para la version 1.8
